In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import wget
wget.download("https://drive.google.com/u/0/uc?id=1_HcM0K8wt4b7FMLkc1V1dv0y6I_9ULzy&export=download")
100% [............................................................................] 684858 / 684858
'Churn_Modelling.csv'
df = pd.read_csv('C:/Users/Dell/PycharmProjects/Android-Malware-Prediction-in-Machine-Learning/Churn_Modelling.csv', index_col=0)
df.head()
CustomerId	Surname	CreditScore	Geography	Gender	Age	Tenure	Balance	NumOfProducts	HasCrCard	IsActiveMember	EstimatedSalary	Exited
RowNumber													
1	15634602	Hargrave	619	France	Female	42	2	0.00	1	1	1	101348.88	1
2	15647311	Hill	608	Spain	Female	41	1	83807.86	1	0	1	112542.58	0
3	15619304	Onio	502	France	Female	42	8	159660.80	3	1	0	113931.57	1
4	15701354	Boni	699	France	Female	39	1	0.00	2	0	0	93826.63	0
5	15737888	Mitchell	850	Spain	Female	43	2	125510.82	1	1	1	79084.10	0
df.columns
Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')
df.shape
(10000, 13)
np.unique(df['Exited'])
array([0, 1], dtype=int64)
#5. Handling Missing values
df.isnull().sum()
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64
#4. Perform descriptive statistics on the dataset.
df.describe(include='all')
CustomerId	Surname	CreditScore	Geography	Gender	Age	Tenure	Balance	NumOfProducts	HasCrCard	IsActiveMember	EstimatedSalary	Exited
count	1.000000e+04	10000	10000.000000	10000	10000	10000.000000	10000.000000	10000.000000	10000.000000	10000.00000	10000.000000	10000.000000	10000.000000
unique	NaN	2932	NaN	3	2	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN
top	NaN	Smith	NaN	France	Male	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN
freq	NaN	32	NaN	5014	5457	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN
mean	1.569094e+07	NaN	650.528800	NaN	NaN	38.921800	5.012800	76485.889288	1.530200	0.70550	0.515100	100090.239881	0.203700
std	7.193619e+04	NaN	96.653299	NaN	NaN	10.487806	2.892174	62397.405202	0.581654	0.45584	0.499797	57510.492818	0.402769
min	1.556570e+07	NaN	350.000000	NaN	NaN	18.000000	0.000000	0.000000	1.000000	0.00000	0.000000	11.580000	0.000000
25%	1.562853e+07	NaN	584.000000	NaN	NaN	32.000000	3.000000	0.000000	1.000000	0.00000	0.000000	51002.110000	0.000000
50%	1.569074e+07	NaN	652.000000	NaN	NaN	37.000000	5.000000	97198.540000	1.000000	1.00000	1.000000	100193.915000	0.000000
75%	1.575323e+07	NaN	718.000000	NaN	NaN	44.000000	7.000000	127644.240000	2.000000	1.00000	1.000000	149388.247500	0.000000
max	1.581569e+07	NaN	850.000000	NaN	NaN	92.000000	10.000000	250898.090000	4.000000	1.00000	1.000000	199992.480000	1.000000
#3. Perform different Visualizations.

    # Univariate Analysis
    # Bi - Variate Analysis
    # Multi - Variate Analysis
plt.scatter(df.index,df['Exited'])

sns.displot(df['Balance'])

sns.rugplot(df['CreditScore'])

sns.scatterplot(x=df['CreditScore'], y=df['Balance'])

sns.boxplot(x='IsActiveMember', y='Exited', data=df)
sns.lmplot(x='Tenure', y='CreditScore', data=df, hue="Exited", fit_reg=False);
#7. Check for Categorical columns and perform encoding.
df['Gender'].unique()
array(['Female', 'Male'], dtype=object)
df['Geography'].unique()
array(['France', 'Spain', 'Germany'], dtype=object)
df['Geography']=preprocessing.LabelEncoder().fit_transform(df['Geography'])
df
CustomerId	Surname	CreditScore	Geography	Gender	Age	Tenure	Balance	NumOfProducts	HasCrCard	IsActiveMember	EstimatedSalary	Exited
RowNumber													
1	15634602	Hargrave	619	0	Female	42	2	0.00	1	1	1	101348.88	1
2	15647311	Hill	608	2	Female	41	1	83807.86	1	0	1	112542.58	0
3	15619304	Onio	502	0	Female	42	8	159660.80	3	1	0	113931.57	1
4	15701354	Boni	699	0	Female	39	1	0.00	2	0	0	93826.63	0
5	15737888	Mitchell	850	2	Female	43	2	125510.82	1	1	1	79084.10	0
...	...	...	...	...	...	...	...	...	...	...	...	...	...
9996	15606229	Obijiaku	771	0	Male	39	5	0.00	2	1	0	96270.64	0
9997	15569892	Johnstone	516	0	Male	35	10	57369.61	1	1	1	101699.77	0
9998	15584532	Liu	709	0	Female	36	7	0.00	1	0	1	42085.58	1
9999	15682355	Sabbatini	772	1	Male	42	3	75075.31	2	1	0	92888.52	1
10000	15628319	Walker	792	0	Female	28	4	130142.79	1	1	0	38190.78	0
10000 rows × 13 columns

df['Gender']=df['Gender'].map({'Male':0,'Female':1})
df
CustomerId	Surname	CreditScore	Geography	Gender	Age	Tenure	Balance	NumOfProducts	HasCrCard	IsActiveMember	EstimatedSalary	Exited
RowNumber													
1	15634602	Hargrave	619	0	1	42	2	0.00	1	1	1	101348.88	1
2	15647311	Hill	608	2	1	41	1	83807.86	1	0	1	112542.58	0
3	15619304	Onio	502	0	1	42	8	159660.80	3	1	0	113931.57	1
4	15701354	Boni	699	0	1	39	1	0.00	2	0	0	93826.63	0
5	15737888	Mitchell	850	2	1	43	2	125510.82	1	1	1	79084.10	0
...	...	...	...	...	...	...	...	...	...	...	...	...	...
9996	15606229	Obijiaku	771	0	0	39	5	0.00	2	1	0	96270.64	0
9997	15569892	Johnstone	516	0	0	35	10	57369.61	1	1	1	101699.77	0
9998	15584532	Liu	709	0	1	36	7	0.00	1	0	1	42085.58	1
9999	15682355	Sabbatini	772	1	0	42	3	75075.31	2	1	0	92888.52	1
10000	15628319	Walker	792	0	1	28	4	130142.79	1	1	0	38190.78	0
10000 rows × 13 columns

#6. Find the outliers and replace the outliers
df.describe()['Balance']
count     10000.000000
mean      76485.889288
std       62397.405202
min           0.000000
25%           0.000000
50%       97198.540000
75%      127644.240000
max      250898.090000
Name: Balance, dtype: float64
def impute_outliers_IQR(df):
    qu1 = df.quantile(0.25)
    qu3 = df.quantile(0.75)
    iqr = qu3 - qu1

    upper = df[~(df > (qu3 + 1.5 * iqr))].max()
    lower = df[~(df < (qu1 - 1.5 * iqr))].min()

    df = np.where(
       df > upper, 
       df.mean(), 
       np.where(df < lower, df.mean(), df)
    )

    return df
df['Balance'] = impute_outliers_IQR(df['Balance'])
df
CustomerId	Surname	CreditScore	Geography	Gender	Age	Tenure	Balance	NumOfProducts	HasCrCard	IsActiveMember	EstimatedSalary	Exited
RowNumber													
1	15634602	Hargrave	619	0	1	42	2	0.00	1	1	1	101348.88	1
2	15647311	Hill	608	2	1	41	1	83807.86	1	0	1	112542.58	0
3	15619304	Onio	502	0	1	42	8	159660.80	3	1	0	113931.57	1
4	15701354	Boni	699	0	1	39	1	0.00	2	0	0	93826.63	0
5	15737888	Mitchell	850	2	1	43	2	125510.82	1	1	1	79084.10	0
...	...	...	...	...	...	...	...	...	...	...	...	...	...
9996	15606229	Obijiaku	771	0	0	39	5	0.00	2	1	0	96270.64	0
9997	15569892	Johnstone	516	0	0	35	10	57369.61	1	1	1	101699.77	0
9998	15584532	Liu	709	0	1	36	7	0.00	1	0	1	42085.58	1
9999	15682355	Sabbatini	772	1	0	42	3	75075.31	2	1	0	92888.52	1
10000	15628319	Walker	792	0	1	28	4	130142.79	1	1	0	38190.78	0
10000 rows × 13 columns

df.describe()['Balance']
count     10000.000000
mean      76485.889288
std       62397.405202
min           0.000000
25%           0.000000
50%       97198.540000
75%      127644.240000
max      250898.090000
Name: Balance, dtype: float64
df.describe()['EstimatedSalary']
count     10000.000000
mean     100090.239881
std       57510.492818
min          11.580000
25%       51002.110000
50%      100193.915000
75%      149388.247500
max      199992.480000
Name: EstimatedSalary, dtype: float64
df['EstimatedSalary'] = impute_outliers_IQR(df['EstimatedSalary'])
df.describe()['EstimatedSalary']
count     10000.000000
mean     100090.239881
std       57510.492818
min          11.580000
25%       51002.110000
50%      100193.915000
75%      149388.247500
max      199992.480000
Name: EstimatedSalary, dtype: float64
def find_outliers_IQR(df):
    qu1=df.quantile(0.25)
    qu3=df.quantile(0.75)
    iqr = qu3 - qu1

    outliers = df[((df < (qu1 - 1.5 * iqr)) | (df > (qu3 + 1.5 * iqr)))]
    return outliers
outliers = find_outliers_IQR(df['EstimatedSalary'])
print(outliers)
Series([], Name: EstimatedSalary, dtype: float64)
print(len(outliers))
print(outliers.max())
print(outliers.min())
0
nan
nan
outliers = find_outliers_IQR(df['Balance'])
print(len(outliers))
print(outliers.max())
print(outliers.min())
0
nan
nan
sns.boxplot(y=df['Balance'])

sns.boxplot(y=df['EstimatedSalary'])

sns.boxplot(y=df['CreditScore'])

outliers = find_outliers_IQR(df['CreditScore'])
print(len(outliers))
print(outliers.max())
print(outliers.min())
0
nan
nan
df['CreditScore'] = impute_outliers_IQR(df['CreditScore'])
df.describe()['CreditScore']
count    10000.000000
mean       650.962593
std         96.000144
min        383.000000
25%        584.000000
50%        652.000000
75%        718.000000
max        850.000000
Name: CreditScore, dtype: float64
sns.boxplot(y=df['CreditScore'])

#8. Split the data into dependent and independent variables
features=list(set(df)-set(['Exited']))
features
['HasCrCard',
 'Gender',
 'IsActiveMember',
 'Age',
 'NumOfProducts',
 'Geography',
 'CustomerId',
 'CreditScore',
 'Tenure',
 'Balance',
 'EstimatedSalary',
 'Surname']
x=df[features].values
x
array([[1, 1, 1, ..., 0.0, 101348.88, 'Hargrave'],
       [0, 1, 1, ..., 83807.86, 112542.58, 'Hill'],
       [1, 1, 0, ..., 159660.8, 113931.57, 'Onio'],
       ...,
       [0, 1, 1, ..., 0.0, 42085.58, 'Liu'],
       [1, 0, 0, ..., 75075.31, 92888.52, 'Sabbatini'],
       [1, 1, 0, ..., 130142.79, 38190.78, 'Walker']], dtype=object)
y=df['Exited'].values
y
array([1, 0, 1, ..., 1, 1, 0], dtype=int64)
df[features]
HasCrCard	Gender	IsActiveMember	Age	NumOfProducts	Geography	CustomerId	CreditScore	Tenure	Balance	EstimatedSalary	Surname
RowNumber												
1	1	1	1	42	1	0	15634602	619.0	2	0.00	101348.88	Hargrave
2	0	1	1	41	1	2	15647311	608.0	1	83807.86	112542.58	Hill
3	1	1	0	42	3	0	15619304	502.0	8	159660.80	113931.57	Onio
4	0	1	0	39	2	0	15701354	699.0	1	0.00	93826.63	Boni
5	1	1	1	43	1	2	15737888	850.0	2	125510.82	79084.10	Mitchell
...	...	...	...	...	...	...	...	...	...	...	...	...
9996	1	0	0	39	2	0	15606229	771.0	5	0.00	96270.64	Obijiaku
9997	1	0	1	35	1	0	15569892	516.0	10	57369.61	101699.77	Johnstone
9998	0	1	1	36	1	0	15584532	709.0	7	0.00	42085.58	Liu
9999	1	0	0	42	2	1	15682355	772.0	3	75075.31	92888.52	Sabbatini
10000	1	1	0	28	1	0	15628319	792.0	4	130142.79	38190.78	Walker
10000 rows × 12 columns

#9. Scale the independent variables
scale = StandardScaler()
x = scale.fit_transform(df[['EstimatedSalary','Balance','CreditScore']])
x
array([[ 0.02188649, -1.22584767, -0.33295983],
       [ 0.21653375,  0.11735002, -0.44754872],
       [ 0.2406869 ,  1.33305335, -1.55176894],
       ...,
       [-1.00864308, -1.22584767,  0.60458564],
       [-0.12523071, -0.02260751,  1.26086748],
       [-1.07636976,  0.85996499,  1.46921091]])
#10. Split the data into training and testing
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=0)
train_x,test_x,train_y,test_y
(array([[ 1.10838187, -1.22584767,  0.16706442],
        [-0.74759209, -0.01289171, -2.33305684],
        [ 1.48746417,  0.57507592, -1.20800227],
        ...,
        [ 1.41441489,  1.35890908,  0.90668363],
        [ 0.84614739, -1.22584767, -0.63505781],
        [ 0.32630495,  0.50630343, -0.29129114]]),
 array([[ 1.61304597,  0.87532296, -0.56213761],
        [ 0.49753166,  0.42442221, -1.33300833],
        [-0.4235611 ,  0.30292727,  0.57333413],
        ...,
        [ 0.72065149,  1.29470288, -0.76006388],
        [-1.54438254,  1.0563022 , -0.0100275 ],
        [ 1.61474887,  0.81611017, -0.81214974]]),
 array([0, 0, 0, ..., 0, 0, 1], dtype=int64),
 array([0, 1, 0, ..., 0, 0, 0], dtype=int64))
 
